import Foundation
import Observation
import SwiftData
import UIKit

/// AI body assessment and daily summaries, both generated by the review model.
@MainActor
@Observable
final class HealthCoach {
    private(set) var isAssessing = false
    private(set) var assessmentError: String?
    private(set) var summarizing: Set<Date> = []
    private(set) var summaryErrors: [Date: String] = [:]
    private(set) var sendingThreads: Set<UUID> = []
    private(set) var chatErrors: [UUID: String] = [:]
    private(set) var planningThreads: Set<UUID> = []
    private(set) var planErrors: [UUID: String] = [:]

    private let context: ModelContext

    init(container: ModelContainer) {
        context = container.mainContext
    }

    // MARK: Assessment

    func assess(profileStore: ProfileStore) {
        guard !isAssessing else { return }
        isAssessing = true
        assessmentError = nil

        let activity = BackgroundActivity("BodyAssessment")
        Task {
            do {
                let client = try OpenRouterClient.fromKeychain()
                let model = AppSettings.reviewModel
                let input = try Self.encode(assessmentPayload(profileStore))
                let response = try await client.chatJSON(model: model, system: Prompts.bodyAssessment, user: [.text(input)])
                let content = AssessmentContent(json: response.json)
                guard !content.headline.isEmpty || !content.overall.isEmpty else {
                    throw OpenRouterError.invalidJSON(response.raw)
                }
                context.insert(BodyAssessment(model: model, content: content, rawResponse: response.raw))
                try context.save()
                NotificationCenterService.notifyIfInBackground(title: "身体评估完成", body: content.headline)
            } catch {
                assessmentError = error.localizedDescription
                NotificationCenterService.notifyIfInBackground(title: "身体评估失败", body: error.localizedDescription)
            }
            isAssessing = false
            activity.end()
        }
    }

    private func assessmentPayload(_ store: ProfileStore) -> [String: Any] {
        let profile = store.profile
        let goal = store.goal
        var profileInfo = Self.profileInfo(profile, goal: goal)
        if let target = profile.targetBodyFatPct { profileInfo["target_body_fat_pct"] = target }

        let measurements = fetch(FetchDescriptor<BodyMeasurement>(sortBy: [SortDescriptor(\.date, order: .reverse)]))
            .prefix(10)
            .map { m -> [String: Any] in
                var entry: [String: Any] = ["date": m.date.formatted(Self.dateFormat)]
                if let v = m.weightKg { entry["weight_kg"] = Self.round1(v) }
                if let v = m.bodyFatPct { entry["body_fat_pct"] = Self.round1(v) }
                if let v = m.waistCm { entry["waist_cm"] = Self.round1(v) }
                if let v = m.scaleBMR { entry["scale_bmr"] = Int(v.rounded()) }
                if let v = m.muscleKg { entry["muscle_kg"] = Self.round1(v) }
                if !m.note.isEmpty { entry["note"] = m.note }
                return entry
            }

        var metricsInfo: [String: Any] = [:]
        if let metrics = store.metrics {
            metricsInfo["weight_kg_used"] = Self.round1(metrics.weightKg)
            metricsInfo["bmi"] = Self.round1(metrics.bmi)
            metricsInfo["bmr_mifflin"] = Int(metrics.bmrMifflin.rounded())
            if let v = metrics.fatMassKg { metricsInfo["fat_mass_kg"] = Self.round1(v) }
            if let v = metrics.leanMassKg { metricsInfo["lean_mass_kg"] = Self.round1(v) }
            if let v = metrics.bmrKatch { metricsInfo["bmr_katch"] = Int(v.rounded()) }
            if let v = metrics.bmrScale { metricsInfo["bmr_scale"] = Int(v.rounded()) }
            if let v = metrics.targetWeightFromBodyFat { metricsInfo["target_weight_from_body_fat_kg"] = Self.round1(v) }
            if let source = goal.bmrSource { metricsInfo["bmr_used_for_target"] = source.title }
            if let lean = metrics.leanMassKg, let goalWeight = profile.goalWeightKg, goalWeight > lean {
                metricsInfo["body_fat_pct_at_goal_weight"] = Self.round1((1 - lean / goalWeight) * 100)
            }
            metricsInfo["weekly_loss_target_pct_of_weight"] = (profile.weeklyLossKg / metrics.weightKg * 1000).rounded() / 10
            metricsInfo["safe_weekly_loss_range_kg"] = "\(Self.round1(metrics.weightKg * 0.005))-\(Self.round1(metrics.weightKg * 0.01))"
            if let goalWeight = profile.goalWeightKg, metrics.weightKg > goalWeight {
                metricsInfo["weeks_to_goal_at_target_rate"] = Int(((metrics.weightKg - goalWeight) / profile.weeklyLossKg).rounded())
            }
        }

        let calendar = Calendar.current
        let start = calendar.date(byAdding: .day, value: -14, to: calendar.startOfDay(for: .now))!
        let meals = fetch(FetchDescriptor<Meal>(predicate: #Predicate { $0.timestamp >= start }))
        let exercises = fetch(FetchDescriptor<ExerciseSession>(predicate: #Predicate { $0.timestamp >= start }))
        let loggedDays = Set(meals.map { calendar.startOfDay(for: $0.timestamp) }).count
        var recent: [String: Any] = [
            "days": 14,
            "logged_days": loggedDays,
            "exercise_sessions": exercises.count,
            "avg_daily_exercise_kcal": Int((exercises.reduce(0) { $0 + $1.netKcal } / 14).rounded()),
        ]
        let trend = weightTrendInfo()
        if loggedDays > 0 {
            let avgKcal = meals.reduce(0) { $0 + $1.totalKcal } / Double(loggedDays)
            let avgProtein = meals.reduce(0) { $0 + $1.totalProtein } / Double(loggedDays)
            recent["avg_kcal_on_logged_days"] = Int(avgKcal.rounded())
            recent["avg_protein_g_on_logged_days"] = Int(avgProtein.rounded())
            if let weight = store.currentWeightKg {
                recent["avg_protein_g_per_kg"] = (avgProtein / weight * 100).rounded() / 100
            }
            if let protein = goal.proteinG { recent["avg_protein_gap_g"] = protein - Int(avgProtein.rounded()) }
            recent["avg_kcal_vs_target"] = Int(avgKcal.rounded()) - goal.kcal
            if let rate = trend["weekly_rate_kg"] as? Double, loggedDays >= 7 {
                // Energy balance: intake + exercise − (weekly change × 7700 / 7) ≈ real daily expenditure.
                let exercisePerDay = exercises.reduce(0) { $0 + $1.netKcal } / 14
                recent["tdee_estimated_from_intake_and_trend"] = Int((avgKcal + exercisePerDay - rate * GoalCalculator.kcalPerKgFat / 7).rounded())
            }
        }
        if let rate = trend["weekly_rate_kg"] as? Double, rate < -0.05,
           let goalWeight = profile.goalWeightKg, let weight = store.currentWeightKg, weight > goalWeight {
            metricsInfo["weeks_to_goal_at_current_rate"] = Int(((weight - goalWeight) / -rate).rounded())
        }

        return [
            "today": Date.now.formatted(Self.dateFormat),
            "profile": profileInfo,
            "measurements": measurements,
            "metrics": metricsInfo,
            "weight_trend": trend,
            "recent": recent,
        ]
    }

    // MARK: Daily summary

    func isSummarizing(_ day: Date) -> Bool { summarizing.contains(Calendar.current.startOfDay(for: day)) }

    func summaryError(_ day: Date) -> String? { summaryErrors[Calendar.current.startOfDay(for: day)] }

    func summarize(day: Date, profileStore: ProfileStore) {
        let day = Calendar.current.startOfDay(for: day)
        guard !summarizing.contains(day) else { return }
        summarizing.insert(day)
        summaryErrors[day] = nil

        let activity = BackgroundActivity("DailySummary")
        Task {
            do {
                let client = try OpenRouterClient.fromKeychain()
                let model = AppSettings.reviewModel
                let isPartial = Calendar.current.isDateInToday(day)
                let input = try Self.encode(dailyPayload(day: day, isPartial: isPartial, store: profileStore))
                let response = try await client.chatJSON(model: model, system: Prompts.dailySummary, user: [.text(input)])
                let content = DailySummaryContent(json: response.json)
                guard !content.headline.isEmpty || !content.diet.isEmpty else {
                    throw OpenRouterError.invalidJSON(response.raw)
                }
                let existing = fetch(FetchDescriptor<DailySummary>(predicate: #Predicate { $0.date == day }))
                existing.forEach(context.delete)
                context.insert(DailySummary(date: day, model: model, isPartial: isPartial, content: content, rawResponse: response.raw))
                try context.save()
                NotificationCenterService.notifyIfInBackground(title: "今日总结已生成", body: content.headline)
            } catch {
                summaryErrors[day] = error.localizedDescription
                NotificationCenterService.notifyIfInBackground(title: "今日总结生成失败", body: error.localizedDescription)
            }
            summarizing.remove(day)
            activity.end()
        }
    }

    private func dailyPayload(day: Date, isPartial: Bool, store: ProfileStore) -> [String: Any] {
        let calendar = Calendar.current
        let profile = store.profile
        let goal = store.goal
        let end = calendar.date(byAdding: .day, value: 1, to: day)!
        let recentStart = calendar.date(byAdding: .day, value: -7, to: day)!

        let meals = fetch(FetchDescriptor<Meal>(predicate: #Predicate { $0.timestamp >= recentStart && $0.timestamp < end },
                                                sortBy: [SortDescriptor(\.timestamp)]))
        let exercises = fetch(FetchDescriptor<ExerciseSession>(predicate: #Predicate { $0.timestamp >= recentStart && $0.timestamp < end },
                                                               sortBy: [SortDescriptor(\.timestamp)]))
        let weights = fetch(FetchDescriptor<WeightEntry>(sortBy: [SortDescriptor(\.date)]))

        let todayMeals = meals.filter { $0.timestamp >= day }
        let todayExercises = exercises.filter { $0.timestamp >= day }
        let exerciseKcal = todayExercises.reduce(0) { $0 + $1.netKcal }
        let budget = goal.budget(exerciseKcal: exerciseKcal, eatBackRatio: profile.eatBackRatio)

        var profileInfo = Self.profileInfo(profile, goal: goal)
        profileInfo["kcal_budget"] = budget
        profileInfo["exercise_eat_back_ratio"] = profile.eatBackRatio

        let todayKcal = todayMeals.reduce(0) { $0 + $1.totalKcal }
        let todayProtein = todayMeals.reduce(0) { $0 + $1.totalProtein }
        var today: [String: Any] = [
            "remaining_kcal": budget - Int(todayKcal.rounded()),
            "date": day.formatted(Self.dateFormat),
            "weekday": day.formatted(.dateTime.weekday(.wide)),
            "kcal": Int(todayKcal.rounded()),
            "protein_g": Int(todayProtein.rounded()),
            "fat_g": Int(todayMeals.reduce(0) { $0 + $1.totalFat }.rounded()),
            "carbs_g": Int(todayMeals.reduce(0) { $0 + $1.totalCarbs }.rounded()),
            "exercise_kcal": Int(exerciseKcal.rounded()),
            "meals": todayMeals.map { meal -> [String: Any] in
                var entry: [String: Any] = [
                    "type": meal.mealType.title,
                    "time": meal.timestamp.formatted(date: .omitted, time: .shortened),
                    "kcal": Int(meal.totalKcal.rounded()),
                    "protein_g": Int(meal.totalProtein.rounded()),
                    "items": meal.sortedItems.map { "\($0.name) \(Int($0.grams.rounded()))g" },
                ]
                if !meal.note.isEmpty { entry["note"] = meal.note }
                return entry
            },
            "exercises": todayExercises.map { session -> [String: Any] in
                [
                    "time": session.timestamp.formatted(date: .omitted, time: .shortened),
                    "description": session.text,
                    "items": session.sortedItems.map { "\($0.name) \(Int($0.durationMin.rounded()))分钟 MET \($0.met)" },
                    "kcal": Int(session.netKcal.rounded()),
                ]
            },
        ]

        if let protein = goal.proteinG { today["protein_remaining_g"] = protein - Int(todayProtein.rounded()) }

        let weightByDay = Dictionary(weights.map { (calendar.startOfDay(for: $0.date), $0.kg) }, uniquingKeysWith: { _, last in last })
        let recentDays: [[String: Any]] = (1...7).reversed().map { offset in
            let date = calendar.date(byAdding: .day, value: -offset, to: day)!
            let next = calendar.date(byAdding: .day, value: 1, to: date)!
            let dayMeals = meals.filter { $0.timestamp >= date && $0.timestamp < next }
            let dayExercises = exercises.filter { $0.timestamp >= date && $0.timestamp < next }
            var info: [String: Any] = [
                "date": date.formatted(Self.dateFormat),
                "weekday": date.formatted(.dateTime.weekday(.wide)),
                "logged": !dayMeals.isEmpty,
            ]
            if !dayMeals.isEmpty {
                info["kcal"] = Int(dayMeals.reduce(0) { $0 + $1.totalKcal }.rounded())
                info["protein_g"] = Int(dayMeals.reduce(0) { $0 + $1.totalProtein }.rounded())
            }
            if !dayExercises.isEmpty {
                info["exercise_kcal"] = Int(dayExercises.reduce(0) { $0 + $1.netKcal }.rounded())
                info["exercises"] = dayExercises.map(\.summaryText)
            }
            if let kg = weightByDay[date] { info["weight_kg"] = Self.round1(kg) }
            return info
        }

        var payload: [String: Any] = [
            "is_in_progress": isPartial,
            "profile": profileInfo,
            "today": today,
            "recent_days": recentDays,
            "recent_summary": recentSummary(recentDays, todayHasExercise: !todayExercises.isEmpty, goal: goal,
                                            eatBackRatio: profile.eatBackRatio),
            "weight_trend": weightTrendInfo(),
        ]
        if isPartial {
            payload["current_time"] = Date.now.formatted(date: .omitted, time: .shortened)
        }
        let latestReview = fetch(FetchDescriptor<WeeklyReview>(sortBy: [SortDescriptor(\.weekStart, order: .reverse)])).first
        if let focus = latestReview?.content?.focus, !focus.isEmpty {
            payload["weekly_focus"] = focus
        }
        if let plan = activePlan()?.content, let planned = plan.day(for: day) {
            payload["training_plan_today"] = planned.isRest
                ? "休息日\(planned.notes.isEmpty ? "" : "：" + planned.notes)"
                : "\(planned.title)：\(planned.exercises.map(\.summary).joined(separator: "；"))"
        }
        return payload
    }

    // MARK: Chat

    func isSending(_ thread: ChatThread) -> Bool { sendingThreads.contains(thread.id) }
    func chatError(_ thread: ChatThread) -> String? { chatErrors[thread.id] }

    /// Appends the user's message (if any) and asks the coach model for a reply.
    func send(_ text: String?, in thread: ChatThread, profileStore: ProfileStore) {
        guard !sendingThreads.contains(thread.id) else { return }
        if let text = text?.trimmingCharacters(in: .whitespacesAndNewlines), !text.isEmpty {
            thread.messages.append(ChatMessage(role: "user", content: text))
            if thread.title.isEmpty || thread.title == "新对话" { thread.title = String(text.prefix(20)) }
        }
        thread.updatedAt = .now
        try? context.save()
        sendingThreads.insert(thread.id)
        chatErrors[thread.id] = nil

        let activity = BackgroundActivity("CoachChat")
        Task {
            do {
                let client = try OpenRouterClient.fromKeychain()
                let system = (thread.isPlanIntake ? Prompts.planIntake : Prompts.coachChat)
                    + "\n" + (try Self.encode(contextSnapshot(profileStore)))
                var messages: [[String: Any]] = [["role": "system", "content": system]]
                messages += thread.sortedMessages.suffix(40).map { ["role": $0.role, "content": $0.content] }
                let reply = try await client.chatText(model: AppSettings.reviewModel, messages: messages)
                thread.messages.append(ChatMessage(role: "assistant", content: reply.trimmingCharacters(in: .whitespacesAndNewlines)))
                thread.updatedAt = .now
                try context.save()
                NotificationCenterService.notifyIfInBackground(title: "教练回复了", body: String(reply.prefix(80)))
            } catch {
                chatErrors[thread.id] = error.localizedDescription
            }
            sendingThreads.remove(thread.id)
            activity.end()
        }
    }

    // MARK: Training plan

    func isPlanning(_ thread: ChatThread) -> Bool { planningThreads.contains(thread.id) }
    func planError(_ thread: ChatThread) -> String? { planErrors[thread.id] }

    func activePlan() -> TrainingPlan? {
        fetch(FetchDescriptor<TrainingPlan>(predicate: #Predicate { $0.isActive },
                                            sortBy: [SortDescriptor(\.createdAt, order: .reverse)])).first
    }

    func generatePlan(from thread: ChatThread, profileStore: ProfileStore) {
        guard !planningThreads.contains(thread.id) else { return }
        planningThreads.insert(thread.id)
        planErrors[thread.id] = nil

        let activity = BackgroundActivity("TrainingPlan")
        Task {
            do {
                let client = try OpenRouterClient.fromKeychain()
                let model = AppSettings.reviewModel
                let payload: [String: Any] = [
                    "user_data": contextSnapshot(profileStore),
                    "conversation": thread.sortedMessages.map { ["role": $0.isUser ? "用户" : "教练", "content": $0.content] },
                ]
                let response = try await client.chatJSON(model: model, system: Prompts.trainingPlan, user: [.text(try Self.encode(payload))])
                let content = PlanContent(json: response.json)
                guard !content.days.isEmpty else { throw OpenRouterError.invalidJSON(response.raw) }
                for plan in fetch(FetchDescriptor<TrainingPlan>(predicate: #Predicate { $0.isActive })) {
                    plan.isActive = false
                }
                context.insert(TrainingPlan(model: model, content: content, rawResponse: response.raw))
                thread.messages.append(ChatMessage(role: "assistant", content: "已生成训练计划「\(content.title)」，可以在「教练」页查看。想调整的话继续告诉我，然后重新生成。"))
                try context.save()
                NotificationCenterService.notifyIfInBackground(title: "训练计划已生成", body: content.title)
            } catch {
                planErrors[thread.id] = error.localizedDescription
                NotificationCenterService.notifyIfInBackground(title: "训练计划生成失败", body: error.localizedDescription)
            }
            planningThreads.remove(thread.id)
            activity.end()
        }
    }

    /// Current state for chat and planning: today's progress, recent week, body metrics and plan.
    private func contextSnapshot(_ store: ProfileStore) -> [String: Any] {
        var snapshot = dailyPayload(day: Calendar.current.startOfDay(for: .now), isPartial: true, store: store)
        snapshot["now"] = Date.now.formatted(.dateTime.year().month().day().weekday(.wide).hour().minute())
        snapshot.removeValue(forKey: "is_in_progress")
        snapshot.removeValue(forKey: "current_time")

        var body: [String: Any] = [:]
        if let metrics = store.metrics {
            body["bmi"] = Self.round1(metrics.bmi)
            if let v = metrics.fatMassKg { body["fat_mass_kg"] = Self.round1(v) }
            if let v = metrics.leanMassKg { body["lean_mass_kg"] = Self.round1(v) }
        }
        if let v = store.body.bodyFatPct { body["body_fat_pct"] = v }
        if let v = store.body.waistCm { body["waist_cm"] = v }
        if let v = store.profile.targetBodyFatPct { body["target_body_fat_pct"] = v }
        if !body.isEmpty { snapshot["body"] = body }

        let assessment = fetch(FetchDescriptor<BodyAssessment>(sortBy: [SortDescriptor(\.createdAt, order: .reverse)])).first
        if let content = assessment?.content {
            snapshot["latest_body_assessment"] = "\(content.headline)。\(content.overall)"
        }
        if let plan = activePlan()?.content {
            snapshot["training_plan"] = [
                "title": plan.title,
                "days": plan.days.map { day -> String in
                    day.isRest ? "\(day.weekdayName) 休息" : "\(day.weekdayName) \(day.title)：\(day.exercises.map(\.summary).joined(separator: "；"))"
                },
            ]
        }
        return snapshot
    }

    /// Counts and lists precomputed here so the model doesn't have to count days or work out weekdays itself.
    private func recentSummary(_ days: [[String: Any]], todayHasExercise: Bool, goal: NutritionGoal,
                               eatBackRatio: Double) -> [String: Any] {
        let logged = days.filter { $0["logged"] as? Bool == true }
        let label: ([String: Any]) -> String = { "\($0["date"] as? String ?? "")（\($0["weekday"] as? String ?? "")）" }
        let budget: ([String: Any]) -> Int = {
            goal.budget(exerciseKcal: Double($0["exercise_kcal"] as? Int ?? 0), eatBackRatio: eatBackRatio)
        }
        var streak = todayHasExercise ? 1 : 0
        if todayHasExercise {
            for day in days.reversed() {
                guard day["exercise_kcal"] != nil else { break }
                streak += 1
            }
        }
        var summary: [String: Any] = [
            "logged_days": "\(logged.count)/\(days.count)",
            "unlogged_days": days.filter { $0["logged"] as? Bool != true }.map(label),
            "exercise_days": days.filter { $0["exercise_kcal"] != nil }.count,
            "consecutive_exercise_days_including_today": streak,
            "days_over_kcal_budget": logged.filter { ($0["kcal"] as? Int ?? 0) > budget($0) }
                .map { "\(label($0)) 摄入 \($0["kcal"] as? Int ?? 0) / 额度 \(budget($0)) kcal" },
        ]
        if !logged.isEmpty {
            summary["avg_kcal_on_logged_days"] = logged.reduce(0) { $0 + ($1["kcal"] as? Int ?? 0) } / logged.count
            summary["avg_protein_g_on_logged_days"] = logged.reduce(0) { $0 + ($1["protein_g"] as? Int ?? 0) } / logged.count
            if let protein = goal.proteinG {
                summary["days_protein_target_met"] = logged.filter { ($0["protein_g"] as? Int ?? 0) >= protein }.count
            }
        }
        return summary
    }

    // MARK: Helpers

    private static let dateFormat = Date.FormatStyle().year().month(.twoDigits).day(.twoDigits)

    private static func round1(_ value: Double) -> Double { (value * 10).rounded() / 10 }

    private static func encode(_ payload: [String: Any]) throws -> String {
        String(decoding: try JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys]), as: UTF8.self)
    }

    private static func profileInfo(_ profile: UserProfile, goal: NutritionGoal) -> [String: Any] {
        var info: [String: Any] = [
            "daily_kcal_target": goal.kcal,
            "kcal_target_is_manual": goal.isManual,
            "safety_floor_kcal": profile.sex == .male ? 1500 : 1200,
        ]
        if profile.isConfigured {
            info["sex"] = profile.sex.title
            info["age"] = profile.age
            info["height_cm"] = profile.heightCm
            info["activity"] = "\(profile.activity.title)（\(profile.activity.detail)）"
            info["weekly_loss_target_kg"] = profile.weeklyLossKg
            if let goalWeight = profile.goalWeightKg { info["goal_weight_kg"] = goalWeight }
        }
        if let protein = goal.proteinG { info["daily_protein_target_g"] = protein }
        if let bmr = goal.bmr { info["bmr"] = bmr }
        if let tdee = goal.tdee { info["tdee"] = tdee }
        return info
    }

    private func weightTrendInfo() -> [String: Any] {
        let points = WeightTrend.compute(fetch(FetchDescriptor<WeightEntry>()))
        guard let last = points.last else { return ["entries": 0] }
        var info: [String: Any] = [
            "entries": points.count,
            "latest_kg": Self.round1(last.kg),
            "latest_date": last.date.formatted(Self.dateFormat),
            "trend_kg": Self.round1(last.trendKg),
        ]
        if let rate = WeightTrend.weeklyRate(points) {
            info["weekly_rate_kg"] = (rate * 100).rounded() / 100
        }
        let monthAgo = last.date.addingTimeInterval(-30 * 86_400)
        if let old = points.last(where: { $0.date <= monthAgo }) {
            info["change_30d_kg"] = Self.round1(last.trendKg - old.trendKg)
        }
        return info
    }

    private func fetch<T: PersistentModel>(_ descriptor: FetchDescriptor<T>) -> [T] {
        (try? context.fetch(descriptor)) ?? []
    }
}
